; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 123

Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Color, 0x00FFFF
Gui Font
Gui Font, s16 cNavy, Noto Sans TC SemiBold
Gui Add, Text, x170 y47 w279 h35 +0x200, 自動下載模組工具 V2.0
Gui Font
Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Add, Text, x251 y108 w342 h0 +0x10
Gui Add, Text, x-18 y108 w1081 h1 +0x10
Gui Font
Gui Font, s11 cPurple, Noto Sans TC Medium
Gui Add, Text, x11 y122 w234 h30 +0x200, 選擇檔案位置(模組、壓縮包)
Gui Font
Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Add, Button, x411 y122 w153 h64, 選擇檔案 (Jar、rar)
Gui Add, Text, x148 y308 w86 h33 +0x200, 模組(jar)
Gui Font
Gui Font, s16
Gui Add, CheckBox, x251 y314 w29 h23
Gui Font
Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Add, Text, x342 y308 w108 h33 +0x200, 模組包(rar)
Gui Font
Gui Font, s16
Gui Add, CheckBox, x463 y315 w29 h23
Gui Font
Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Add, Button, x239 y350 w126 h64, 開始安裝
Gui Font
Gui Font, s11 cPurple, Noto Sans TC Medium
Gui Add, Text, x7 y224 w234 h30 +0x200, 指定解壓縮位置(預設mods)
Gui Font
Gui Font, s12 cBlue, Noto Sans TC Medium
Gui Add, Edit, x253 y124 w145 h61
Gui Add, Edit, x254 y218 w143 h66
Gui Add, Button, x414 y219 w150 h64, 選擇模組資料夾位置

Gui Show, w620 h420, 自動安裝模組工具 V2.0
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }

Return

GuiEscape:
GuiClose:
    ExitApp
